all: points.ml

points.ml: points.txt Makefile.points
	echo "let test_ps = [" > points.ml
	cat points.txt | grep black | sed -r 's/^([0-9]+),([0-9]+).*$$/    (\1, \2);/' | sort -n >> points.ml
	echo "]" >> points.ml

points.txt: points.png
	convert points.png points.txt

