all: points.coord.txt Makefile.points

points.coord.txt: points.txt
	cat points.txt | grep black | sed -r 's/^([0-9]+),([0-9]+).*$$/\1 \2/' | sort -n > points.coord.txt

points.txt: points.png
	convert points.png points.txt

